# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.operation import Operation

class TestOperation(unittest.TestCase):
    """Operation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Operation:
        """Test Operation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Operation`
        """
        model = Operation()
        if include_optional:
            return Operation(
                id = '128f274395254cf17eda6b3eb3d021b9',
                status = 'completed',
                created = openapi_client.models.action.Action(
                    user = openapi_client.models.user.User(
                        id = 'V1ZVd2VyFzU3NiQ1NDA4NjIzNzk2MjD', 
                        user_name = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    date_time = '2019-10-30T15:03:27Z', ),
                updated = openapi_client.models.action.Action(
                    user = openapi_client.models.user.User(
                        id = 'V1ZVd2VyFzU3NiQ1NDA4NjIzNzk2MjD', 
                        user_name = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    date_time = '2019-10-30T15:03:27Z', ),
                resource_url = '',
                original_request = '7bee78f7-417b-42bc-ace9-e588c65d19bf',
                details = [{"message":"Attempted to modify locked cells"}]
            )
        else:
            return Operation(
        )
        """

    def testOperation(self):
        """Test Operation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
