# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.spreadsheet import Spreadsheet

class TestSpreadsheet(unittest.TestCase):
    """Spreadsheet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Spreadsheet:
        """Test Spreadsheet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Spreadsheet`
        """
        model = Spreadsheet()
        if include_optional:
            return Spreadsheet(
                id = '124efa2a142f472ba1ceab34ed18915f',
                name = 'Year-end review',
                template = False,
                created = openapi_client.models.action.Action(
                    user = openapi_client.models.user.User(
                        id = 'V1ZVd2VyFzU3NiQ1NDA4NjIzNzk2MjD', 
                        user_name = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    date_time = '2019-10-30T15:03:27Z', ),
                modified = openapi_client.models.action.Action(
                    user = openapi_client.models.user.User(
                        id = 'V1ZVd2VyFzU3NiQ1NDA4NjIzNzk2MjD', 
                        user_name = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    date_time = '2019-10-30T15:03:27Z', ),
                sheets = [
                    openapi_client.models.sheet.Sheet(
                        id = '27f1b61c04ae4b0991bc73c631914e1d', 
                        name = 'Q1', 
                        parent = openapi_client.models.sheet.Sheet(
                            id = '27f1b61c04ae4b0991bc73c631914e1d', 
                            name = 'Q1', 
                            index = 1, 
                            children = [
                                
                                ], 
                            dataset = openapi_client.models.dataset.Dataset(
                                sheet = '27f1b61c04ae4b0991bc73c631914e1d', 
                                range = 'A1:B2', 
                                values = [[1,4],[2,""]], ), ), 
                        index = 1, 
                        children = [
                            
                            ], 
                        dataset = openapi_client.models.dataset.Dataset(
                            sheet = '27f1b61c04ae4b0991bc73c631914e1d', 
                            range = 'A1:B2', 
                            values = [[1,4],[2,""]], ), )
                    ]
            )
        else:
            return Spreadsheet(
        )
        """

    def testSpreadsheet(self):
        """Test Spreadsheet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
