# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document import Document

class TestDocument(unittest.TestCase):
    """Document unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Document:
        """Test Document
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Document`
        """
        model = Document()
        if include_optional:
            return Document(
                id = '124efa2a142f472ba1ceab34ed18915f',
                name = 'Example Company 10-K',
                template = False,
                created = openapi_client.models.action.Action(
                    user = openapi_client.models.user.User(
                        id = 'V1ZVd2VyFzU3NiQ1NDA4NjIzNzk2MjD', 
                        user_name = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    date_time = '2019-10-30T15:03:27Z', ),
                modified = openapi_client.models.action.Action(
                    user = openapi_client.models.user.User(
                        id = 'V1ZVd2VyFzU3NiQ1NDA4NjIzNzk2MjD', 
                        user_name = '', 
                        display_name = '', 
                        first_name = '', 
                        last_name = '', 
                        email = '', ), 
                    date_time = '2019-10-30T15:03:27Z', ),
                sections = [
                    {"id":"a8b3adb687644b27fafcb3a9875f0f0d_18","name":"Risk factors","parent":null,"index":1,"children":[],"nonPrinting":false}
                    ]
            )
        else:
            return Document(
        )
        """

    def testDocument(self):
        """Test Document"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
