# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sheet_update_delete_columns import SheetUpdateDeleteColumns

class TestSheetUpdateDeleteColumns(unittest.TestCase):
    """SheetUpdateDeleteColumns unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SheetUpdateDeleteColumns:
        """Test SheetUpdateDeleteColumns
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SheetUpdateDeleteColumns`
        """
        model = SheetUpdateDeleteColumns()
        if include_optional:
            return SheetUpdateDeleteColumns(
                intervals = [
                    openapi_client.models.interval.Interval(
                        start = 0, 
                        end = 0, )
                    ],
                force = True
            )
        else:
            return SheetUpdateDeleteColumns(
                intervals = [
                    openapi_client.models.interval.Interval(
                        start = 0, 
                        end = 0, )
                    ],
        )
        """

    def testSheetUpdateDeleteColumns(self):
        """Test SheetUpdateDeleteColumns"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
