# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.presentation_to_pdf_options import PresentationToPdfOptions

class TestPresentationToPdfOptions(unittest.TestCase):
    """PresentationToPdfOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PresentationToPdfOptions:
        """Test PresentationToPdfOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PresentationToPdfOptions`
        """
        model = PresentationToPdfOptions()
        if include_optional:
            return PresentationToPdfOptions(
                include_hyperlinks = True,
                include_leader_dots = True,
                include_alternate_row_fill = True,
                tag_for_web_accessibility = True,
                use_cmyk_colorspace = True,
                include_draft_watermark = True,
                include_comments = True
            )
        else:
            return PresentationToPdfOptions(
        )
        """

    def testPresentationToPdfOptions(self):
        """Test PresentationToPdfOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
