# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_to_pdf_options import DocumentToPdfOptions

class TestDocumentToPdfOptions(unittest.TestCase):
    """DocumentToPdfOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentToPdfOptions:
        """Test DocumentToPdfOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentToPdfOptions`
        """
        model = DocumentToPdfOptions()
        if include_optional:
            return DocumentToPdfOptions(
                include_hyperlinks = True,
                include_leader_dots = True,
                include_alternate_row_fill = True,
                tag_for_web_accessibility = True,
                include_attachment_labels = True,
                use_cmyk_colorspace = True,
                include_draft_watermark = True,
                include_comments = True,
                include_track_changes = True
            )
        else:
            return DocumentToPdfOptions(
        )
        """

    def testDocumentToPdfOptions(self):
        """Test DocumentToPdfOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
