# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.presentation_export import PresentationExport

class TestPresentationExport(unittest.TestCase):
    """PresentationExport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PresentationExport:
        """Test PresentationExport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PresentationExport`
        """
        model = PresentationExport()
        if include_optional:
            return PresentationExport(
                format = 'pdf',
                slides = ["a8b3adb687644b27fafcb3a9875f0f0d_18","a8b3adb687644b27fafcb3a9875f0f0d_19"],
                pdf_options = openapi_client.models.presentation_to_pdf_options.PresentationToPdfOptions(
                    include_hyperlinks = True, 
                    include_leader_dots = True, 
                    include_alternate_row_fill = True, 
                    tag_for_web_accessibility = True, 
                    use_cmyk_colorspace = True, 
                    include_draft_watermark = True, 
                    include_comments = True, ),
                pptx_options = openapi_client.models.presentation_to_pptx_options.PresentationToPptxOptions(
                    include_unused_layout_slides = True, )
            )
        else:
            return PresentationExport(
                format = 'pdf',
        )
        """

    def testPresentationExport(self):
        """Test PresentationExport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
