# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_export import DocumentExport

class TestDocumentExport(unittest.TestCase):
    """DocumentExport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentExport:
        """Test DocumentExport
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentExport`
        """
        model = DocumentExport()
        if include_optional:
            return DocumentExport(
                format = 'pdf',
                sections = ["a8b3adb687644b27fafcb3a9875f0f0d_18","a8b3adb687644b27fafcb3a9875f0f0d_19"],
                pdf_options = openapi_client.models.document_to_pdf_options.DocumentToPdfOptions(
                    include_hyperlinks = True, 
                    include_leader_dots = True, 
                    include_alternate_row_fill = True, 
                    tag_for_web_accessibility = True, 
                    include_attachment_labels = True, 
                    use_cmyk_colorspace = True, 
                    include_draft_watermark = True, 
                    include_comments = True, 
                    include_track_changes = True, ),
                docx_options = openapi_client.models.document_to_docx_options.DocumentToDocxOptions(
                    include_leader_dots = True, 
                    show_table_cell_shading = True, ),
                xhtml_options = openapi_client.models.document_to_xhtml_options.DocumentToXhtmlOptions(
                    include_external_hyperlinks = True, 
                    include_headers_and_footers = True, 
                    editable_xhtml = True, 
                    editable_simple = True, )
            )
        else:
            return DocumentExport(
                format = 'pdf',
        )
        """

    def testDocumentExport(self):
        """Test DocumentExport"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
