# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_forms_api import TestFormsApi


class TestTestFormsApi(unittest.TestCase):
    """TestFormsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestFormsApi()

    def tearDown(self) -> None:
        pass

    def test_create_matrix(self) -> None:
        """Test case for create_matrix

        Create a new matrix
        """
        pass

    def test_create_sample(self) -> None:
        """Test case for create_sample

        Create a new sample
        """
        pass

    def test_get_matrices(self) -> None:
        """Test case for get_matrices

        Retrieve a list of matrices
        """
        pass

    def test_get_matrix_attachment_by_id(self) -> None:
        """Test case for get_matrix_attachment_by_id

        Retrieve a single matrix attachment
        """
        pass

    def test_get_matrix_attachments(self) -> None:
        """Test case for get_matrix_attachments

        Retrieve a list of matrix attachments
        """
        pass

    def test_get_matrix_by_id(self) -> None:
        """Test case for get_matrix_by_id

        Retrieve a single matrix
        """
        pass

    def test_get_sample_attachment_by_id(self) -> None:
        """Test case for get_sample_attachment_by_id

        Retrieve a single sample attachment
        """
        pass

    def test_get_sample_attachments(self) -> None:
        """Test case for get_sample_attachments

        Retrieve a list of sample attachments
        """
        pass

    def test_get_sample_by_id(self) -> None:
        """Test case for get_sample_by_id

        Retrieve a single sample
        """
        pass

    def test_get_samples(self) -> None:
        """Test case for get_samples

        Retrieve a list of samples
        """
        pass

    def test_get_test_form_by_id(self) -> None:
        """Test case for get_test_form_by_id

        Retrieve a single test form
        """
        pass

    def test_get_test_forms(self) -> None:
        """Test case for get_test_forms

        Retrieve a list of test forms
        """
        pass

    def test_get_test_phase_attachment_by_id(self) -> None:
        """Test case for get_test_phase_attachment_by_id

        Retrieve a single test phase attachment
        """
        pass

    def test_get_test_phase_attachments(self) -> None:
        """Test case for get_test_phase_attachments

        Retrieve a list of test phase attachments
        """
        pass

    def test_get_test_phase_by_id(self) -> None:
        """Test case for get_test_phase_by_id

        Retrive a single test phase
        """
        pass

    def test_get_test_phases(self) -> None:
        """Test case for get_test_phases

        Retrieve a list of test phases
        """
        pass

    def test_matrix_attachment_download_by_id(self) -> None:
        """Test case for matrix_attachment_download_by_id

        Initiate a matrix attachment download
        """
        pass

    def test_matrix_attachment_export_by_id(self) -> None:
        """Test case for matrix_attachment_export_by_id

        Initiate an export of a matrix attachment
        """
        pass

    def test_matrix_attachment_upload(self) -> None:
        """Test case for matrix_attachment_upload

        Initiate a matrix attachment upload
        """
        pass

    def test_partially_update_sample_by_id(self) -> None:
        """Test case for partially_update_sample_by_id

        Partially update a single sample
        """
        pass

    def test_sample_attachment_download_by_id(self) -> None:
        """Test case for sample_attachment_download_by_id

        Initiate a download of a sample attachment
        """
        pass

    def test_sample_attachment_export_by_id(self) -> None:
        """Test case for sample_attachment_export_by_id

        Initiate an export of a sample attachment
        """
        pass

    def test_sample_attachment_upload(self) -> None:
        """Test case for sample_attachment_upload

        Initiate an upload of a sample attachment
        """
        pass

    def test_sample_insertion(self) -> None:
        """Test case for sample_insertion

        Insert samples
        """
        pass

    def test_sample_update(self) -> None:
        """Test case for sample_update

        Update samples
        """
        pass

    def test_test_form_export(self) -> None:
        """Test case for test_form_export

        Initiate a test form export
        """
        pass

    def test_test_phase_attachment_download_by_id(self) -> None:
        """Test case for test_phase_attachment_download_by_id

        Initiate a test phase attachment download
        """
        pass

    def test_test_phase_attachment_export_by_id(self) -> None:
        """Test case for test_phase_attachment_export_by_id

        Initiate a test phase attachment export
        """
        pass

    def test_test_phase_attachment_upload(self) -> None:
        """Test case for test_phase_attachment_upload

        Initiate a test phase attachment upload
        """
        pass

    def test_update_sample_by_id(self) -> None:
        """Test case for update_sample_by_id

        Update a single sample
        """
        pass


if __name__ == '__main__':
    unittest.main()
