# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.apply_borders import ApplyBorders

class TestApplyBorders(unittest.TestCase):
    """ApplyBorders unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyBorders:
        """Test ApplyBorders
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyBorders`
        """
        model = ApplyBorders()
        if include_optional:
            return ApplyBorders(
                ranges = [
                    openapi_client.models.range.Range(
                        start_row = 0, 
                        stop_row = 0, 
                        start_column = 0, 
                        stop_column = 0, )
                    ],
                top = {"style":"SINGLE","weight":2,"color":"#000000"},
                bottom = {"style":"SINGLE","weight":2,"color":"#000000"},
                left = {"style":"SINGLE","weight":2,"color":"#000000"},
                right = {"style":"SINGLE","weight":2,"color":"#000000"},
                inner_horizontal = {"style":"SINGLE","weight":2,"color":"#000000"},
                inner_vertical = {"style":"SINGLE","weight":2,"color":"#000000"}
            )
        else:
            return ApplyBorders(
                ranges = [
                    openapi_client.models.range.Range(
                        start_row = 0, 
                        stop_row = 0, 
                        start_column = 0, 
                        stop_column = 0, )
                    ],
        )
        """

    def testApplyBorders(self):
        """Test ApplyBorders"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
