# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.graph_api import GraphApi


class TestGraphApi(unittest.TestCase):
    """GraphApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GraphApi()

    def tearDown(self) -> None:
        pass

    def test_create_edits(self) -> None:
        """Test case for create_edits

        Create new record edits
        """
        pass

    def test_get_record_by_id(self) -> None:
        """Test case for get_record_by_id

        Retrieve a single record
        """
        pass

    def test_get_records(self) -> None:
        """Test case for get_records

        Retrieve a list of records
        """
        pass

    def test_get_report_as_csv(self) -> None:
        """Test case for get_report_as_csv

        Retrieve the CSV of a saved report
        """
        pass

    def test_get_type_by_id(self) -> None:
        """Test case for get_type_by_id

        Retrieve a single type
        """
        pass

    def test_get_types(self) -> None:
        """Test case for get_types

        Retrieve a list of types
        """
        pass

    def test_graph_report_export(self) -> None:
        """Test case for graph_report_export

        Initiate a graph report export
        """
        pass


if __name__ == '__main__':
    unittest.main()
