# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.graph_attachment_upload import GraphAttachmentUpload

class TestGraphAttachmentUpload(unittest.TestCase):
    """GraphAttachmentUpload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphAttachmentUpload:
        """Test GraphAttachmentUpload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphAttachmentUpload`
        """
        model = GraphAttachmentUpload()
        if include_optional:
            return GraphAttachmentUpload(
                file_name = 'signature.jpg'
            )
        else:
            return GraphAttachmentUpload(
        )
        """

    def testGraphAttachmentUpload(self):
        """Test GraphAttachmentUpload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
