# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.sample_cell import SampleCell

class TestSampleCell(unittest.TestCase):
    """SampleCell unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleCell:
        """Test SampleCell
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleCell`
        """
        model = SampleCell()
        if include_optional:
            return SampleCell(
                column = '235cdb36-f93d-4f15-bac9-1c3a52c2aefa',
                value = '304.45'
            )
        else:
            return SampleCell(
        )
        """

    def testSampleCell(self):
        """Test SampleCell"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
