# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.matrix import Matrix

class TestMatrix(unittest.TestCase):
    """Matrix unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Matrix:
        """Test Matrix
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Matrix`
        """
        model = Matrix()
        if include_optional:
            return Matrix(
                id = '30053df2-75fa-4a1e-9e8c-0e18cdd66cd1',
                name = 'Purchase Orders',
                data_columns = [{"id":"d795d7a3-e7f7-4b3f-be6a-109653b2929b","name":"PO Number","externalId":"TA05"},{"id":"fbd818ec-4fd1-42ad-9112-3c80e71dc2dc","name":"Amount","externalId":"TA06"}],
                result_columns = [{"id":"d795d7a3-e7f7-4b3f-be6a-109653b2c34d","name":"A","externalId":"TA07"}],
                samples = [{"id":"ce4a6c7f-15ad-445c-a76a-f457d53f667a","dataValues":[{"column":"425c","value":123},{"column":"425d","value":101.1}],"resultValues":[{"column":"c05f","value":"PASS"}]}],
                attachments = [{"id":"d795d7a3-e7f7-4b3f-be6a-109653b2929b","fileName":"process.pdf"}]
            )
        else:
            return Matrix(
        )
        """

    def testMatrix(self):
        """Test Matrix"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
