# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_create_task(self) -> None:
        """Test case for create_task

        Create a new task
        """
        pass

    def test_delete_task_by_id(self) -> None:
        """Test case for delete_task_by_id

        Delete a single task
        """
        pass

    def test_get_task_by_id(self) -> None:
        """Test case for get_task_by_id

        Retrieve a single task
        """
        pass

    def test_get_tasks(self) -> None:
        """Test case for get_tasks

        Retrieve a list of tasks
        """
        pass

    def test_partially_update_task_by_id(self) -> None:
        """Test case for partially_update_task_by_id

        Partially update a single task
        """
        pass

    def test_update_task_by_id(self) -> None:
        """Test case for update_task_by_id

        Update a single task
        """
        pass


if __name__ == '__main__':
    unittest.main()
