# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.value_format_period_format import ValueFormatPeriodFormat

class TestValueFormatPeriodFormat(unittest.TestCase):
    """ValueFormatPeriodFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValueFormatPeriodFormat:
        """Test ValueFormatPeriodFormat
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValueFormatPeriodFormat`
        """
        model = ValueFormatPeriodFormat()
        if include_optional:
            return ValueFormatPeriodFormat(
                display = 'RAW',
                separator = 'COMMA',
                precision = 0,
                show_labels = True,
                show_numbers_as_words = True,
                capitalize_first_word = True
            )
        else:
            return ValueFormatPeriodFormat(
                display = 'RAW',
        )
        """

    def testValueFormatPeriodFormat(self):
        """Test ValueFormatPeriodFormat"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
