# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InheritFrom(str, Enum):
    """
    Where to inherit formats from when performing an insertion
    """

    """
    allowed enum values
    """
    NONE = 'NONE'
    BEFORE = 'BEFORE'
    AFTER = 'AFTER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InheritFrom from a JSON string"""
        return cls(json.loads(json_str))


