# coding: utf-8

"""
    Platform API

    Use the Workiva Platform API to programmatically manage items in the Workiva platform, such as files, folders, tasks, comments, documents, spreadsheets, and presentations. 

    The version of the OpenAPI document: v1
    Contact: platformsupport@workiva.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.graph_attachment import GraphAttachment
from openapi_client.models.sample_cell import SampleCell
from typing import Optional, Set
from typing_extensions import Self

class MatrixSample(BaseModel):
    """
    This object represents a single row of a matrix.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="The unique ID of the matrix sample")
    data_values: Optional[List[SampleCell]] = Field(default=None, description="An array of SampleCell values representing the values for each data column of the sample matrix's cells", alias="dataValues")
    result_values: Optional[List[SampleCell]] = Field(default=None, description="An array of SampleCell values representing the values for each result cell in the sample matrix's cells.", alias="resultValues")
    attachments: Optional[List[GraphAttachment]] = Field(default=None, description="An optional array of partial information about the attachments on the matrix sample. To include in the response, provide the query parameter `$expand=attachments`.")
    __properties: ClassVar[List[str]] = ["id", "dataValues", "resultValues", "attachments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MatrixSample from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "attachments",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data_values (list)
        _items = []
        if self.data_values:
            for _item_data_values in self.data_values:
                if _item_data_values:
                    _items.append(_item_data_values.to_dict())
            _dict['dataValues'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in result_values (list)
        _items = []
        if self.result_values:
            for _item_result_values in self.result_values:
                if _item_result_values:
                    _items.append(_item_result_values.to_dict())
            _dict['resultValues'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MatrixSample from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "dataValues": [SampleCell.from_dict(_item) for _item in obj["dataValues"]] if obj.get("dataValues") is not None else None,
            "resultValues": [SampleCell.from_dict(_item) for _item in obj["resultValues"]] if obj.get("resultValues") is not None else None,
            "attachments": [GraphAttachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None
        })
        return _obj


